name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        if: success()
        run: npm run build:ci
      - name: Save build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
      - name: Deploy to Github Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.x
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: production
          base_href: /ng-budget/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/ng-budget
