name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy to Github Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          build_configuration: production
          base_href: /ng-budget/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/ng-budget
